<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoWarn>$(NoWarn);NETSDK1206</NoWarn>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FundMarket.Database\FundMarket.Database.csproj" />
      <ProjectReference Include="..\FundMarket.Reader\FundMarket.Reader.csproj" />
    </ItemGroup>

</Project>
